on:
  push:
    branches:
      - development

name: development

jobs:
  ContinuousIntegration:
    name: Run Build, Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Build Apps
        run: composer install

      # - name: Run Unit Tests
      #   run: vendor/bin/phpunit

      - name: Standart Pint
        run: ./vendor/bin/pint
